---
name: Gerrit Tox Verify

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      GERRIT_REFSPEC:
        description: "Gerrit refspec of change"
        required: true
        type: string
      GERRIT_CHANGE_NUMBER:
        description: "The Gerrit change number. TODO: Parse from refspec."
        required: true
        type: string
      GERRIT_PATCHSET_NUMBER:
        description: "The patch number for the change. TODO: Parse from refspec."
        required: true
        type: string
      GERRIT_EVENT_TYPE:
        description: "Type of Gerrit event."
        required: true
        type: string
        default: "patchset-created"

concurrency:
  # yamllint disable-line rule:line-length
  group: gerrit-csit-tox-verify-${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true

jobs:
  clear-votes:
    runs-on: ubuntu-latest
    steps:
      - name: Clear votes
        uses: lfit/gerrit-review-action@v0.4
        with:
          host: ${{ vars.GERRIT_SERVER }}
          username: ${{ vars.GERRIT_SSH_REQUIRED_USER }}
          key: ${{ secrets.GERRIT_SSH_REQUIRED_PRIVKEY }}
          known_hosts: ${{ vars.GERRIT_KNOWN_HOSTS }}
          gerrit-change-number: ${{ inputs.GERRIT_CHANGE_NUMBER }}
          gerrit-patchset-number: ${{ inputs.GERRIT_PATCHSET_NUMBER }}
          vote-type: clear
          comment-only: true
      - name: Allow replication
        run: sleep 10s
  run-tox:
    runs-on: ubuntu-latest
    steps:
      - name: Gerrit checkout
        # yamllint disable-line rule:line-length
        uses: lfit/checkout-gerrit-change-action@54d751e8bd167bc91f7d665dabe33fae87aaaa63  # v0.9
        with:
          gerrit-url: "https://gerrit.fd.io/r/"
          repository: "fdio/csit"
          gerrit-project: "csit"
          gerrit-refspec: ${{ inputs.GERRIT_REFSPEC }}
          ref: ${{ inputs.GERRIT_REFSPEC }}
          fetch-depth: 2
          submodules: true
          delay: "0s"
      - name: Run tox
        shell: bash
        run: |
          set -exuo pipefail
          source ./resources/libraries/bash/entry/tox.sh

  vote:
    if: ${{ always() }}
    # yamllint enable rule:line-length
    needs: [clear-votes, run-tox]
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - name: Set vote
        uses: lfit/gerrit-review-action@v0.4
        with:
          host: ${{ vars.GERRIT_SERVER }}
          username: ${{ vars.GERRIT_SSH_REQUIRED_USER }}
          key: ${{ secrets.GERRIT_SSH_REQUIRED_PRIVKEY }}
          known_hosts: ${{ vars.GERRIT_KNOWN_HOSTS }}
          gerrit-change-number: ${{ inputs.GERRIT_CHANGE_NUMBER }}
          gerrit-patchset-number: ${{ inputs.GERRIT_PATCHSET_NUMBER }}
          vote-type: ${{ env.WORKFLOW_CONCLUSION }}
          comment-only: false
